# Generated by Django 6.0.7 on 2026-07-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa / Rubro')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('ocean_o', models.IntegerField(default=50, verbose_name='Apertura (Openness)')),
                ('ocean_c', models.IntegerField(default=50, verbose_name='Responsabilidad (Conscientiousness)')),
                ('ocean_e', models.IntegerField(default=50, verbose_name='Extraversión (Extraversion)')),
                ('ocean_a', models.IntegerField(default=50, verbose_name='Amabilidad (Agreeableness)')),
                ('ocean_n', models.IntegerField(default=50, verbose_name='Neuroticismo (Neuroticism)')),
                ('comportamiento_compra', models.CharField(blank=True, max_length=100, verbose_name='Comportamiento de Compra')),
                ('estilo_decision', models.CharField(blank=True, max_length=100, verbose_name='Estilo de Decisión')),
                ('disparadores_compra', models.TextField(blank=True, null=True, verbose_name='Disparadores de Venta')),
                ('intereses', models.TextField(blank=True, null=True, verbose_name='Intereses Clave')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
